2019-12-26 23:51:16,084 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
2019-12-26 23:52:37,848 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
2019-12-26 23:58:56,203 ERROR: Exception on /dashboard [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\pydasci\app\dashboard\routes.py", line 15, in dashboard
    if articles['id']>0:
TypeError: list indices must be integers, not str
2019-12-27 00:01:11,644 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
2019-12-27 00:01:16,605 ERROR: Exception on /dashboard [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\pydasci\app\dashboard\routes.py", line 16, in dashboard
    return render_template('dashbaord/articles.html',articles=articles,title='Articles')
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: dashbaord/articles.html
2019-12-27 00:02:10,052 ERROR: Exception on /dashboard [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\pydasci\app\dashboard\routes.py", line 16, in dashboard
    return render_template('dashbaord/articles.html',articles=articles,title='Articles')
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: dashbaord/articles.html
2019-12-27 00:03:26,221 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
2019-12-27 00:03:36,404 ERROR: Exception on /dashboard [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\pydasci\app\dashboard\routes.py", line 16, in dashboard
    return render_template('dashbaord/articles.html',articles=articles,title='Articles')
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: dashbaord/articles.html
2019-12-27 00:06:17,358 INFO: Microblog startup [in app\__init__.py:79]
2019-12-27 00:06:36,884 INFO: Microblog startup [in app\__init__.py:79]
2019-12-27 00:06:36,884 INFO: Microblog startup [in app\__init__.py:79]
2019-12-27 00:20:37,677 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
2019-12-27 00:21:07,334 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
2019-12-27 00:22:26,413 INFO: Microblog startup [in app\__init__.py:79]
2019-12-27 00:22:29,016 INFO: Microblog startup [in app\__init__.py:79]
2019-12-27 00:22:29,016 INFO: Microblog startup [in app\__init__.py:79]
2019-12-27 00:26:06,970 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
