2019-12-26 19:57:02,526 ERROR: Exception on /index [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Samuel\Desktop\pydasci\app\main\routes.py", line 30, in index
    return render_template('index.html', title=('Home'))
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\index.html", line 4, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 34, in top-level template code
    <a class="nav-link" href="{{url_for('articles.article')}}">Article</a>
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'articles.article'. Did you mean 'main.index' instead?
2019-12-26 19:58:35,404 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 19:58:43,565 ERROR: Exception on / [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Samuel\Desktop\pydasci\app\main\routes.py", line 30, in index
    return render_template('index.html', title=('Home'))
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\index.html", line 4, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 34, in top-level template code
    <a class="nav-link" href="{{url_for('articles.article')}}">Article</a>
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'articles.article'. Did you mean 'main.index' instead?
2019-12-26 19:58:47,398 ERROR: Exception on / [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Samuel\Desktop\pydasci\app\main\routes.py", line 30, in index
    return render_template('index.html', title=('Home'))
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\index.html", line 4, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 34, in top-level template code
    <a class="nav-link" href="{{url_for('articles.article')}}">Article</a>
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'articles.article'. Did you mean 'main.index' instead?
2019-12-26 19:59:22,148 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 19:59:31,698 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 20:00:35,328 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 20:00:48,671 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
