2019-12-26 20:20:03,690 ERROR: Exception on /article [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Samuel\Desktop\pydasci\app\articles\routes.py", line 11, in article
    return render_template('articles/article.html', title=('Article'), form=form)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\articles\article.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 41, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\articles\article.html", line 6, in block "app_content"
    <h1>{{ wtf.form_field(title) }} </h1>
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 36, in template
    {% if field.flags.required and not required in kwargs %}
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'str object' has no attribute 'flags'
2019-12-26 20:20:10,532 ERROR: Exception on /article [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Samuel\Desktop\pydasci\app\articles\routes.py", line 11, in article
    return render_template('articles/article.html', title=('Article'), form=form)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\articles\article.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 41, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\articles\article.html", line 6, in block "app_content"
    <h1>{{ wtf.form_field(title) }} </h1>
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 36, in template
    {% if field.flags.required and not required in kwargs %}
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'str object' has no attribute 'flags'
2019-12-26 20:21:05,999 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 20:21:11,552 ERROR: Exception on /article [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Samuel\Desktop\pydasci\app\articles\routes.py", line 11, in article
    return render_template('articles/article.html', title=('Article'), form=form)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\articles\article.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 41, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\articles\article.html", line 6, in block "app_content"
    <h1>{{ wtf.form_field(title) }} </h1>
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 36, in template
    {% if field.flags.required and not required in kwargs %}
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'str object' has no attribute 'flags'
2019-12-26 20:24:29,221 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 20:33:28,562 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 20:52:02,331 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 20:52:20,819 ERROR: Exception on /article [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Samuel\Desktop\pydasci\app\articles\routes.py", line 11, in article
    if current_user.is_authenticated:
NameError: global name 'current_user' is not defined
2019-12-26 20:53:09,334 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 21:22:52,947 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
